### ISSUE TITLE
Missing CallScreen import folders

### ISSUE THREAD

**Issue by negbie** [datso/react-native-pjsip-app#12]
Hi,
the build was successfull but i get:

ledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 782): UnableToResolveError: Unable to resolve module ../../components/Call/CallState from /home/negbie/Git/react-native-pjsip-app/app/screens/CallScreen/index.js: Directory /home/negbie/Git/react-native-pjsip-app/app/components/Call/CallState doesn't exist

when i look into react-native-pjsip-app/app/components/Call/ i see only
CallAvatar  
DtmfModal

So i can't import
import CallState from '../../components/Call/CallState'
import CallInfo from '../../components/Call/CallInfo'
import CallAction from '../../components/Call/CallAction'
import CallControls from '../../components/Call/CallControls'
import CallActions from '../../components/Call/CallActions'
import CallParallelInfo from '../../components/Call/CallParallelInfo'
import TransferModal from '../../components/Call/TransferModal'
import DialerModal from '../../components/Call/DialerModal'
import IncomingCallModal from '../../components/Call/IncomingCallModal'

did i miss something?

**Comment by datso** [comment]
Hi, please move `CallAvatar` & `DtmfModal` to call folder and after that rename call to Call folder. This should fix problem locally.

**Comment by negbie** [comment]
Damit did not see that call folder ;) Thank you. That fixed it.
