### ISSUE TITLE
"Unable to resolve module ../../components/Call/CallState" on Ubuntu

### ISSUE THREAD

**Issue by madox2** [datso/react-native-pjsip-app#13]
Hi, I am runing this app on Ubuntu and after installing I am getting error:
`Unable to resolve module ../../components/Call/CallState`.

The problem is that linux system use case sensitive paths and filenames (unlike mac). Therefore the solution would be to merge `app/components/Call/` and `app/components/call/` directory.

**Comment by datso** [comment]
Thanks, I will change it.
