### ISSUE TITLE
Settings aren't saved after reload application

### ISSUE THREAD

**Issue by segrey11** [datso/react-native-pjsip-app#14]
Hi!
I've built the application from the source code and launched it on my phone. I successfully registered on my SIP server but I noticed that after relaunching application I lost my sip account settings. It seems that account settings are not stored.  Could you please help me?
I did the tests on Xiaomi Redmi note3(MTK) with android 5.0.2 and Motorola MotoX Play with Android 6.0.1

**Comment by datso** [comment]
Hello, this app is still in early stage of development. I've going to add this feature and a lot of other ones later.
