### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by anvesh523** [datso/react-native-pjsip-app#16]
I'm getting this error message while running the project. Please help me with this error.

**Comment by anvesh523** [comment]
I'm sharing the screenshots. Might be these will help for better understanding. Just downloaded the code and run it. 

![screenshot_1500379073](https://user-images.githubusercontent.com/10726276/28316010-8f40bd30-6bde-11e7-98f5-6f7d3f06dbbf.png)
![screenshot_1500379081](https://user-images.githubusercontent.com/10726276/28316011-8f46d3e6-6bde-11e7-997c-ecf08017a201.png)
![screenshot_1500379087](https://user-images.githubusercontent.com/10726276/28316008-8f390fc2-6bde-11e7-88c7-8a43407fc4d3.png)
![screenshot_1500379092](https://user-images.githubusercontent.com/10726276/28316009-8f3cf86c-6bde-11e7-9f17-8be58823011e.png)

**Comment by datso** [comment]
Hi, this issue is not with app itself, check your emulator whether it could connect to RN dev server.

**Comment by anvesh523** [comment]
The same error is coming in both my emulator and my phone. Please explain "whether it could connect to RN dev server". Like what I have to do to slove..!
