### ISSUE TITLE
cant able to run on android 

### ISSUE THREAD

**Issue by 9meAhmed** [datso/react-native-pjsip-app#17]
i am new at react i am trying to run this app on android but having errror: 
cannot get batchbridge

**Comment by anvesh523** [comment]
Open one more node js terminal and type "react-native start". After that you can run the project in other terminal. I think it will run.

**Comment by 9meAhmed** [comment]
![image](https://user-images.githubusercontent.com/17180707/28415654-1991068e-6d6a-11e7-8609-d01c648013a7.png)
 getting this

**Comment by datso** [comment]
npm install
react-native run-android

> ensure that emulator/phone has access to your dev server (firewalls, etc..)
https://facebook.github.io/react-native/docs/running-on-device.html

> you can also build .apk 
https://facebook.github.io/react-native/docs/signed-apk-android.html
