### ISSUE TITLE
STUCKED ON LOADING

### ISSUE THREAD

**Issue by jojonarte** [datso/react-native-pjsip-app#2]
I've tried cloning this repo then npm install
then react-native run-android
The screenshot below shows how it is without change.

http://screencast.com/t/Izep4SnM

**Comment by datso** [comment]
Hi, at the moment this application is still in development :)
If you are interested in PjSip for Android, consider using this library [react-native-pjsip](https://github.com/datso/react-native-pjsip). 

I have a plan to finish this app in 2 months.
