### ISSUE TITLE
react-native-pjsip@2.7.4 postinstall: `bash libs.sh`

### ISSUE THREAD

**Issue by mounirlahsini** [datso/react-native-pjsip-app#37]
PS C:\Users\mouni\react-native-pjsip-app> npm install
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
PS C:\Users\mouni\react-native-pjsip-app> npm install
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead

> react-native-pjsip@2.7.4 postinstall C:\Users\mouni\react-native-pjsip-app\node_modules\react-native-pjsip
> bash libs.sh

'bash' is not recognized as an internal or external command,
operable program or batch file.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN The package react is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-pjsip@2.7.4 postinstall: `bash libs.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-pjsip@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mouni\AppData\Roaming\npm-cache\_logs\2018-05-17T21_16_39_405Z-debug.log
PS C:\Users\mouni\react-native-pjsip-app>

**Comment by ananbetak** [comment]
why this has been closed ?! i face the same problem !!!

**Comment by datso** [comment]
PR are welcome.

**Comment by ProMasoud** [comment]
you should to use a Terminal that support `bash` command. personally I use `git bash` in windows. [download here](https://git-scm.com/downloads)

**Comment by dinukasal** [comment]
If you get this on linux run with this command,
`ionice -n2 yarn add react-native-pjsip` or `ionice -n2 npm install react-native-pjsip`
I got it working. 
As I understand this is because the `libs.sh` script is downloading a 70mb+ tar file from a slow server,
so if you are running in linux the process get a low priority and finally gets terminated by a timeout.
To overcome you have to assign a high priority to the process with `ionice` command.
