### ISSUE TITLE
RCTBundleURLProvider.h file not found

### ISSUE THREAD

**Issue by zziazm** [datso/react-native-pjsip-app#5]
i have downloaded it and built but it has error:RCTBundleURLProvider.h file not found

**Comment by datso** [comment]
Hi, seems that problem not in pjsip wrapper for react.
Btw wrapper for iOS is not ready yet, try Android version.

**Comment by TimMeade** [comment]
We are playing with this now….

Android we have working.

Should the IOS compile and run at all?  We are getting to a promise error.

Thanks

Tim

**Comment by datso** [comment]
As I remember iOS should compile but there is only registration functionality.

**Comment by rachelxj** [comment]
so is there any way to test iOS video? Looking forward to someone could make it work. :)
