### ISSUE TITLE
Not able to make  Outbound

### ISSUE THREAD

**Issue by murugancmi** [datso/react-native-pjsip-app#7]
When i try to make outbound call, getting timeout screen every time

**Comment by datso** [comment]
Hi, check whether you have correct SIP configuration, try to call from another SIP client.
Also provide adb logs.

**Comment by murugancmi** [comment]
If my sip configuration is wrong,How i can receive inbound ,Even  inbound call work only 4 or 5 time.

**Comment by datso** [comment]
Ok, attach adb logs.

**Comment by murugancmi** [comment]
03-01 15:37:19.869   306  8686 D libc-netbsd: res_queryN name = voip.telecmi.com succeed
03-01 15:37:19.870  7821  7889 D libc-netbsd: getaddrinfo: voip.telecmi.com get result from proxy gai_error = 0
03-01 15:37:19.871  7821  7889 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:19.871  7821  7889 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:19.871  7821  7889 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:19.891  7821  7821 D PjSipBroadcastReceiver: Received "com.carusto.call.changed" response from service ({"data":"{\"id\":3,\"callId\":\"d84vFjxoF.BIx7SREcveMyn.aaBtkZ1e\",\"accountId\":0,\"localContact\":\"\u003csip:1_1111112@157.50.6.89:33780;ob\u003e\",\"localUri\":\"murugan \u003csip:1_1111112@voip.telecmi.com\u003e\",\"remoteContact\":\"\",\"remoteUri\":\"sip:919894396168@voip.telecmi.com\",\"state\":\"PJSIP_INV_STATE_CALLING\",\"stateText\":\"CALLING\",\"connectDuration\":-1,\"totalDuration\":0,\"held\":false,\"muted\":false,\"speaker\":false,\"lastReason\":\"\",\"remoteOfferer\":false,\"remoteAudioCount\":0,\"remoteVideoCount\":0,\"audioCount\":1,\"videoCount\":1}"})
03-01 15:37:19.904  7821  7821 D PjSipBroadcastReceiver: Received "com.carusto.handled" response from service ({"callback_id":3,"data":"{\"id\":3,\"callId\":\"d84vFjxoF.BIx7SREcveMyn.aaBtkZ1e\",\"accountId\":0,\"localContact\":\"\u003csip:1_1111112@157.50.6.89:33780;ob\u003e\",\"localUri\":\"murugan \u003csip:1_1111112@voip.telecmi.com\u003e\",\"remoteContact\":\"\",\"remoteUri\":\"sip:919894396168@voip.telecmi.com\",\"state\":\"PJSIP_INV_STATE_CALLING\",\"stateText\":\"CALLING\",\"connectDuration\":-1,\"totalDuration\":0,\"held\":false,\"muted\":false,\"speaker\":false,\"lastReason\":\"\",\"remoteOfferer\":false,\"remoteAudioCount\":0,\"remoteVideoCount\":0,\"audioCount\":1,\"videoCount\":1}"})
03-01 15:37:20.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:20.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:20.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:21.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:21.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:21.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:23.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:23.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:23.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:27.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:27.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:27.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:35.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:35.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:35.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:46.236   873  1300 I ActivityManager: getRecentTasks tr = TaskRecord{ab79f79 #185 A=com.whatsapp:voip U=0 sz=0}
03-01 15:37:51.377  7821  7925 D PjSipLogWriter: INVITE sip:919894396168@voip.telecmi.com SIP/2.0
03-01 15:37:51.377  7821  7925 D PjSipLogWriter: From: "murugan" <sip:1_1111112@voip.telecmi.com>;tag=-Uh7U60DjzSFeymHMAJO9VN0TX3LG1Pp
03-01 15:37:51.377  7821  7925 D PjSipLogWriter: To: sip:919894396168@voip.telecmi.com
03-01 15:37:51.889  7821  7821 D PjSipBroadcastReceiver: Received "com.carusto.call.terminated" response from service ({"data":"{\"id\":3,\"callId\":\"d84vFjxoF.BIx7SREcveMyn.aaBtkZ1e\",\"accountId\":0,\"localContact\":\"\u003csip:1_1111112@157.50.6.89:33780;ob\u003e\",\"localUri\":\"murugan \u003csip:1_1111112@voip.telecmi.com\u003e\",\"remoteContact\":\"\",\"remoteUri\":\"sip:919894396168@voip.telecmi.com\",\"state\":\"PJSIP_INV_STATE_DISCONNECTED\",\"stateText\":\"DISCONNCTD\",\"connectDuration\":0,\"totalDuration\":32,\"held\":false,\"muted\":false,\"speaker\":false,\"lastStatusCode\":\"PJSIP_SC_REQUEST_TIMEOUT\",\"lastReason\":\"Request Timeout\",\"remoteOfferer\":false,\"remoteAudioCount\":0,\"remoteVideoCount\":0,\"audioCount\":1,\"videoCount\":1}"})

**Comment by murugancmi** [comment]
why we need a video here in sdp  ,"remoteVideoCount":0,"audioCount":1,"videoCount":1

**Comment by datso** [comment]
Provide full log, I cant determine what the problem is from our message.
* Also embeed it as a file please
